export type PhoneCountryCodeOption = {
  regionCode: string;
  dialCode: string;
};

export const PHONE_COUNTRY_CODE_OPTIONS: PhoneCountryCodeOption[] = [
  { regionCode: "AF", dialCode: "+93" },
  { regionCode: "AX", dialCode: "+358 18" },
  { regionCode: "AL", dialCode: "+355" },
  { regionCode: "DZ", dialCode: "+213" },
  { regionCode: "AS", dialCode: "+1 684" },
  { regionCode: "AD", dialCode: "+376" },
  { regionCode: "AO", dialCode: "+244" },
  { regionCode: "AI", dialCode: "+1 264" },
  { regionCode: "AQ", dialCode: "+672" },
  { regionCode: "AG", dialCode: "+1 268" },
  { regionCode: "AR", dialCode: "+54" },
  { regionCode: "AM", dialCode: "+374" },
  { regionCode: "AW", dialCode: "+297" },
  { regionCode: "AU", dialCode: "+61" },
  { regionCode: "AT", dialCode: "+43" },
  { regionCode: "AZ", dialCode: "+994" },
  { regionCode: "BS", dialCode: "+1 242" },
  { regionCode: "BH", dialCode: "+973" },
  { regionCode: "BD", dialCode: "+880" },
  { regionCode: "BB", dialCode: "+1 246" },
  { regionCode: "BY", dialCode: "+375" },
  { regionCode: "BE", dialCode: "+32" },
  { regionCode: "BZ", dialCode: "+501" },
  { regionCode: "BJ", dialCode: "+229" },
  { regionCode: "BM", dialCode: "+1 441" },
  { regionCode: "BT", dialCode: "+975" },
  { regionCode: "BO", dialCode: "+591" },
  { regionCode: "BA", dialCode: "+387" },
  { regionCode: "BW", dialCode: "+267" },
  { regionCode: "BR", dialCode: "+55" },
  { regionCode: "IO", dialCode: "+246" },
  { regionCode: "VG", dialCode: "+1 284" },
  { regionCode: "BN", dialCode: "+673" },
  { regionCode: "BG", dialCode: "+359" },
  { regionCode: "BF", dialCode: "+226" },
  { regionCode: "BI", dialCode: "+257" },
  { regionCode: "KH", dialCode: "+855" },
  { regionCode: "CM", dialCode: "+237" },
  { regionCode: "CA", dialCode: "+1" },
  { regionCode: "CV", dialCode: "+238" },
  { regionCode: "KY", dialCode: "+1 345" },
  { regionCode: "CF", dialCode: "+236" },
  { regionCode: "TD", dialCode: "+235" },
  { regionCode: "CL", dialCode: "+56" },
  { regionCode: "CN", dialCode: "+86" },
  { regionCode: "CX", dialCode: "+61" },
  { regionCode: "CC", dialCode: "+61" },
  { regionCode: "CO", dialCode: "+57" },
  { regionCode: "KM", dialCode: "+269" },
  { regionCode: "CG", dialCode: "+242" },
  { regionCode: "CD", dialCode: "+243" },
  { regionCode: "CK", dialCode: "+682" },
  { regionCode: "CR", dialCode: "+506" },
  { regionCode: "CI", dialCode: "+225" },
  { regionCode: "HR", dialCode: "+385" },
  { regionCode: "CU", dialCode: "+53" },
  { regionCode: "CW", dialCode: "+599" },
  { regionCode: "CY", dialCode: "+357" },
  { regionCode: "CZ", dialCode: "+420" },
  { regionCode: "DK", dialCode: "+45" },
  { regionCode: "DJ", dialCode: "+253" },
  { regionCode: "DM", dialCode: "+1 767" },
  { regionCode: "DO", dialCode: "+1 809" },
  { regionCode: "EC", dialCode: "+593" },
  { regionCode: "EG", dialCode: "+20" },
  { regionCode: "SV", dialCode: "+503" },
  { regionCode: "GQ", dialCode: "+240" },
  { regionCode: "ER", dialCode: "+291" },
  { regionCode: "EE", dialCode: "+372" },
  { regionCode: "SZ", dialCode: "+268" },
  { regionCode: "ET", dialCode: "+251" },
  { regionCode: "FK", dialCode: "+500" },
  { regionCode: "FO", dialCode: "+298" },
  { regionCode: "FJ", dialCode: "+679" },
  { regionCode: "FI", dialCode: "+358" },
  { regionCode: "FR", dialCode: "+33" },
  { regionCode: "GF", dialCode: "+594" },
  { regionCode: "PF", dialCode: "+689" },
  { regionCode: "GA", dialCode: "+241" },
  { regionCode: "GM", dialCode: "+220" },
  { regionCode: "GE", dialCode: "+995" },
  { regionCode: "DE", dialCode: "+49" },
  { regionCode: "GH", dialCode: "+233" },
  { regionCode: "GI", dialCode: "+350" },
  { regionCode: "GR", dialCode: "+30" },
  { regionCode: "GL", dialCode: "+299" },
  { regionCode: "GD", dialCode: "+1 473" },
  { regionCode: "GP", dialCode: "+590" },
  { regionCode: "GU", dialCode: "+1 671" },
  { regionCode: "GT", dialCode: "+502" },
  { regionCode: "GG", dialCode: "+44 1481" },
  { regionCode: "GN", dialCode: "+224" },
  { regionCode: "GW", dialCode: "+245" },
  { regionCode: "GY", dialCode: "+592" },
  { regionCode: "HT", dialCode: "+509" },
  { regionCode: "HN", dialCode: "+504" },
  { regionCode: "HK", dialCode: "+852" },
  { regionCode: "HU", dialCode: "+36" },
  { regionCode: "IS", dialCode: "+354" },
  { regionCode: "IN", dialCode: "+91" },
  { regionCode: "ID", dialCode: "+62" },
  { regionCode: "IR", dialCode: "+98" },
  { regionCode: "IQ", dialCode: "+964" },
  { regionCode: "IE", dialCode: "+353" },
  { regionCode: "IM", dialCode: "+44 1624" },
  { regionCode: "IL", dialCode: "+972" },
  { regionCode: "IT", dialCode: "+39" },
  { regionCode: "JM", dialCode: "+1 876" },
  { regionCode: "JP", dialCode: "+81" },
  { regionCode: "JE", dialCode: "+44 1534" },
  { regionCode: "JO", dialCode: "+962" },
  { regionCode: "KZ", dialCode: "+7" },
  { regionCode: "KE", dialCode: "+254" },
  { regionCode: "KI", dialCode: "+686" },
  { regionCode: "KW", dialCode: "+965" },
  { regionCode: "KG", dialCode: "+996" },
  { regionCode: "LA", dialCode: "+856" },
  { regionCode: "LV", dialCode: "+371" },
  { regionCode: "LB", dialCode: "+961" },
  { regionCode: "LS", dialCode: "+266" },
  { regionCode: "LR", dialCode: "+231" },
  { regionCode: "LY", dialCode: "+218" },
  { regionCode: "LI", dialCode: "+423" },
  { regionCode: "LT", dialCode: "+370" },
  { regionCode: "LU", dialCode: "+352" },
  { regionCode: "MO", dialCode: "+853" },
  { regionCode: "MG", dialCode: "+261" },
  { regionCode: "MW", dialCode: "+265" },
  { regionCode: "MY", dialCode: "+60" },
  { regionCode: "MV", dialCode: "+960" },
  { regionCode: "ML", dialCode: "+223" },
  { regionCode: "MT", dialCode: "+356" },
  { regionCode: "MH", dialCode: "+692" },
  { regionCode: "MQ", dialCode: "+596" },
  { regionCode: "MR", dialCode: "+222" },
  { regionCode: "MU", dialCode: "+230" },
  { regionCode: "YT", dialCode: "+262" },
  { regionCode: "MX", dialCode: "+52" },
  { regionCode: "FM", dialCode: "+691" },
  { regionCode: "MD", dialCode: "+373" },
  { regionCode: "MC", dialCode: "+377" },
  { regionCode: "MN", dialCode: "+976" },
  { regionCode: "ME", dialCode: "+382" },
  { regionCode: "MS", dialCode: "+1 664" },
  { regionCode: "MA", dialCode: "+212" },
  { regionCode: "MZ", dialCode: "+258" },
  { regionCode: "MM", dialCode: "+95" },
  { regionCode: "NA", dialCode: "+264" },
  { regionCode: "NR", dialCode: "+674" },
  { regionCode: "NP", dialCode: "+977" },
  { regionCode: "NL", dialCode: "+31" },
  { regionCode: "NC", dialCode: "+687" },
  { regionCode: "NZ", dialCode: "+64" },
  { regionCode: "NI", dialCode: "+505" },
  { regionCode: "NE", dialCode: "+227" },
  { regionCode: "NG", dialCode: "+234" },
  { regionCode: "NU", dialCode: "+683" },
  { regionCode: "NF", dialCode: "+672" },
  { regionCode: "KP", dialCode: "+850" },
  { regionCode: "MK", dialCode: "+389" },
  { regionCode: "MP", dialCode: "+1 670" },
  { regionCode: "NO", dialCode: "+47" },
  { regionCode: "OM", dialCode: "+968" },
  { regionCode: "PK", dialCode: "+92" },
  { regionCode: "PW", dialCode: "+680" },
  { regionCode: "PS", dialCode: "+970" },
  { regionCode: "PA", dialCode: "+507" },
  { regionCode: "PG", dialCode: "+675" },
  { regionCode: "PY", dialCode: "+595" },
  { regionCode: "PE", dialCode: "+51" },
  { regionCode: "PH", dialCode: "+63" },
  { regionCode: "PN", dialCode: "+64" },
  { regionCode: "PL", dialCode: "+48" },
  { regionCode: "PT", dialCode: "+351" },
  { regionCode: "PR", dialCode: "+1 787" },
  { regionCode: "QA", dialCode: "+974" },
  { regionCode: "RE", dialCode: "+262" },
  { regionCode: "RO", dialCode: "+40" },
  { regionCode: "RU", dialCode: "+7" },
  { regionCode: "RW", dialCode: "+250" },
  { regionCode: "BL", dialCode: "+590" },
  { regionCode: "SH", dialCode: "+290" },
  { regionCode: "KN", dialCode: "+1 869" },
  { regionCode: "LC", dialCode: "+1 758" },
  { regionCode: "MF", dialCode: "+590" },
  { regionCode: "PM", dialCode: "+508" },
  { regionCode: "VC", dialCode: "+1 784" },
  { regionCode: "WS", dialCode: "+685" },
  { regionCode: "SM", dialCode: "+378" },
  { regionCode: "ST", dialCode: "+239" },
  { regionCode: "SA", dialCode: "+966" },
  { regionCode: "SN", dialCode: "+221" },
  { regionCode: "RS", dialCode: "+381" },
  { regionCode: "SC", dialCode: "+248" },
  { regionCode: "SL", dialCode: "+232" },
  { regionCode: "SG", dialCode: "+65" },
  { regionCode: "SX", dialCode: "+1 721" },
  { regionCode: "SK", dialCode: "+421" },
  { regionCode: "SI", dialCode: "+386" },
  { regionCode: "SB", dialCode: "+677" },
  { regionCode: "SO", dialCode: "+252" },
  { regionCode: "ZA", dialCode: "+27" },
  { regionCode: "KR", dialCode: "+82" },
  { regionCode: "SS", dialCode: "+211" },
  { regionCode: "ES", dialCode: "+34" },
  { regionCode: "LK", dialCode: "+94" },
  { regionCode: "SD", dialCode: "+249" },
  { regionCode: "SR", dialCode: "+597" },
  { regionCode: "SJ", dialCode: "+47" },
  { regionCode: "SE", dialCode: "+46" },
  { regionCode: "CH", dialCode: "+41" },
  { regionCode: "SY", dialCode: "+963" },
  { regionCode: "TW", dialCode: "+886" },
  { regionCode: "TJ", dialCode: "+992" },
  { regionCode: "TZ", dialCode: "+255" },
  { regionCode: "TH", dialCode: "+66" },
  { regionCode: "TL", dialCode: "+670" },
  { regionCode: "TG", dialCode: "+228" },
  { regionCode: "TK", dialCode: "+690" },
  { regionCode: "TO", dialCode: "+676" },
  { regionCode: "TT", dialCode: "+1 868" },
  { regionCode: "TN", dialCode: "+216" },
  { regionCode: "TR", dialCode: "+90" },
  { regionCode: "TM", dialCode: "+993" },
  { regionCode: "TC", dialCode: "+1 649" },
  { regionCode: "TV", dialCode: "+688" },
  { regionCode: "UG", dialCode: "+256" },
  { regionCode: "UA", dialCode: "+380" },
  { regionCode: "AE", dialCode: "+971" },
  { regionCode: "GB", dialCode: "+44" },
  { regionCode: "US", dialCode: "+1" },
  { regionCode: "UY", dialCode: "+598" },
  { regionCode: "UZ", dialCode: "+998" },
  { regionCode: "VU", dialCode: "+678" },
  { regionCode: "VA", dialCode: "+39" },
  { regionCode: "VE", dialCode: "+58" },
  { regionCode: "VN", dialCode: "+84" },
  { regionCode: "VI", dialCode: "+1 340" },
  { regionCode: "WF", dialCode: "+681" },
  { regionCode: "EH", dialCode: "+212" },
  { regionCode: "YE", dialCode: "+967" },
  { regionCode: "ZM", dialCode: "+260" },
  { regionCode: "ZW", dialCode: "+263" },
];

export function getPhoneCountryLabel(regionCode: string, dialCode: string, locale: string) {
  const displayNames = new Intl.DisplayNames(
    [locale.startsWith("zh") ? "zh-CN" : "en"],
    { type: "region" }
  );
  const regionName = displayNames.of(regionCode) ?? regionCode;
  return `${regionName} (${dialCode})`;
}
